### ISSUE TITLE
Canvas vs. SVG

### ISSUE THREAD

**Issue by stormecharette** [maine-cyber/mcsc-unisim#1]
Until now we've been researching the HTML canvas element as a render target for UniSim.  
I came across an older spec that we should take a look at: Scalable Vector Graphics (SVG). 

At a glance SVG looks more equipped for our needs than canvas. It comes equipped with a scene graph which canvas does not. This means it can keep track of individual objects natively (we'd have to write this ourselves with canvas) and we can interact and animate on a per-object basis. It also has CSS animation support.  SVG is pure XML, scripted by JavaScript, and embeds in HTML nicely.

SVG and canvas can do mostly the same things, it's more about picking the right tool for the job.  

@ksabochick could you look into SVG and compare/contrast with canvas? Some pros and cons for both might help us decide. There are a lot of direct comparison articles out there.

**Comment by ksabochick** [comment]
**Canvas vs SVG Information:**
SVG has a much easier way of inheriting and referencing objects through XML. The vector graphics, while we might not use them, could be useful for the future. The best advantage of using SVG is object interactivity and object definition through javascript.

There's a good breakdown of it here: [https://msdn.microsoft.com/en-us/library/gg193983(v=vs.85).aspx](url) 

SVG is easily embedded into HTML scripts, and CSS/Javascript can be used separately as before. I will add more as I keep experimenting with it.
