### ISSUE TITLE
UniSim is a Registered Trademark

### ISSUE THREAD

**Issue by stormecharette** [maine-cyber/mcsc-unisim#6]
It turns out UniSim is a registered trademark of Honeywell International, Inc. The UniSim Design Suite is a well-known industrial simulation software family. 

Since our UniSim stands for "Universal Simulation", I propose we rebrand to "Universal Simulation Software" or USS. I know acronyms are uncool, but USS is simple and easy to remember. 

@ksabochick what do you think?

**Comment by ksabochick** [comment]
Storme,

Isn't USS a registered trademark/at least owned by the United State Navy?

**Comment by stormecharette** [comment]
No, it's not.

**Comment by stormecharette** [comment]
It's more of a product recognition problem than a trademark issue. Clients won't confuse our software with United States Ships, but they may confuse it with the actual UniSim software.

**Comment by stormecharette** [comment]
Opening new, updated naming issue.
