### ISSUE TITLE
Debug of ConfigObject

### ISSUE THREAD

**Issue by ksabochick** [maine-cyber/mcsc-unisim#61]
## Current Debugging Results for ConfigObject
_December 28th 2016_

Constructors/destructor, insertion, size, and exist() all work fine. As previously discussed, the issues lie with the typeDefs.

### TODOs
The TODOs listed in the code involve creating accessors for more types of values. Specifically mentioned are:

1. **getSigned/UnsignedInt()** - as of right now, ConfigObject cannot hold signed integers. For example, using
       `configObject.insert("signedInt", Val("-500"))`
and then trying to access it with
       `configObject.getInt("signedInt")`
returns 0.

2. **getDouble()** - as of right now, ConfigObject cannot hold double-precision data types.

### Casting and Multi-Types
As of right now, each value can only be assigned to one data type. 

1. "0" or "1" is assigned as an int - it needs to be able to be cast as a boolean.
2. There is currently no support for the following types by **access:**
      - SignedInt/UnsignedInt (see above)
      - Short/SignedShort/UnsignedShort
      - Long/SignedLong/UnsignedLong
      - LongLong/SignedLongLong/UnsignedLongLong
      - Double
      - Char (may not be necessary as we have String)

    As a result, we need to create a dependency tree that assigns multiple types to certain kinds of data values.
3. However, using typeOf() to detect the _type_ of the value has mixed results. For example:
      `configObject.insert("signedInt", Val("-500");`
      `configObject.typeOf("signedInt") == sk::Type::SignedInt;`
returns true. It does NOT return true for SignedShort, SignedLong, or Int (each value can only have one data type).

**Comment by stormecharette** [comment]
I fixed these issues in my branch. The changes will work their way to `development`.  

I added full multi-type support and accessors for every supported type. Some type names have changed, they are all in `<sk/Common/Enums/Types.hpp>`.  

Type are now checked using bitwise operations. For example, if you want to know if a type is a `char` you would use:  

```cpp
if( config_obj.typeOf("mydata") & sk::Type::Char )
{
    // Do something...
}
```  

This can be used to check for multiple types at once using bitwise OR `|`. You can also check the absolute type of an element by using `==` with a series of OR'd types:  

```cpp
if( config_obj.typeOf("mydata") == (sk::Type::Int | sk::Type::UnsignedInt) )
{
   // Do something else...
}
```

@ksabochick, let me know if you run into any problems with the new ConfigObject accessors or any more const issues.
