### ISSUE TITLE
Debug of Socket

### ISSUE THREAD

**Issue by ksabochick** [maine-cyber/mcsc-unisim#71]
## Current Debugging Results for Socket
_January 12th 2017_

### ServerSocket
The following issues were discovered in ServerSocket. Some may be intentional and/or irrelevant.

- [x]  **isListening():** As of right now, once the server socket is set to "listen," it will continue to return true when isListening() is called, even after the socket is closed or terminated.
- [x]  **bind():** When bind is called on more than one server address in succession, the socket fails to bind to any address. For example, 
`server.bind(server_addr);  server.bind(server_addr_2);` 
returns an error and termination. This occurs both when the server addresses are identical and when they are different.
- [x] **accept(), send(), receive():** When accept, send, or receive is called more than once in succession, the socket stalls out and does not connect to the client at all. It does not return an error, but waits infinitely.

### LocalStream
The following issue was discovered using LocalStream.

- [x] **Remaining files:** When the files are created with the server address, they appear as desired. However, once the socket is closed the files remain in the system. (This may or may not be intentional, as discussed).

**Comment by stormecharette** [comment]
Thank you for this.  

The `bind()` and hanging process issues are OK. Blocking behavior is typical in default sockets. There is a blocking switch on both Server and Client sockets, which ensures that functions will never block.  

I fixed the `isListening()` bug. It will return false if the socket is invalid/closed.  

I fixed the server file bug. A local addressing server will remove its file upon destruction.
